### ISSUE TITLE
Plans for pdf support?

### ISSUE THREAD

**Issue by BrianChevalier** [Kamik423/equalize#3]
Hi are there any plans to bring pdf output support?

**Comment by Kamik423** [comment]
How do you imagine this looking?

Just an A4/Letter PDF with the equation in the middle? Or a stamp sized PDF with just the equation?

I never considered it, because I did not think of a use case. What are you thinking of using it for?

**Comment by BrianChevalier** [comment]
Same size as the png export but basically just as a tiny pdf document. The reason is because it provides a transparent background and there’s no pixelation with scaling that doesn’t distort the image. I’ve attached a picture of my use case in civil engineering. One of the theta_A equations are made with equalize the other with TeXEquation. It’s not a huge difference but for production quality work it is important to work with vector graphics.

![20dd97ab-6a5a-4e26-baa2-b26ec9e0b2c8](https://user-images.githubusercontent.com/19725742/40502771-df346796-5f40-11e8-8ff5-d101ffb7822a.png)

**Comment by Kamik423** [comment]
Implemented in the latest beta
